#!/usr/bin/env bash
# script that configures an Ubuntu server
cp /etc/hosts /etc/new_hosts

sed -i '/localhost/d' /etc/hosts

echo "127.0.0.2 localhost" >> /etc/new_host
echo "8.8.8.8 facebook.com" >> /etc/new_host

cp /etc/new_host /etc/hosts